### ISSUE TITLE
Change interface FsxDirectoryEntry.name to FsxDirectoryEntry.filePath (or "fileOrDirPath"?)

### ISSUE THREAD

**Issue by MorganConrad** [humanwhocodes/humanfs#53]
### Which packages would you like to change?

- [ ] `fsx-core`
- [ ] `fsx-node`
- [ ] `fsx-deno`
- [ ] `fsx-memory`
- [ ] `fsx-web`
- [ ] `fsx-test`
- [X] `fsx-types`

### What problem do you want to solve?

`.name` is the property used by node fs (in fs.Dirent), and there is is just the filename, not the path.  New users of fsx may mistakenly think the same.  Instead, FsxDirectoryEntry should use `.filePath`, or possibly `.fileOrDirPath`.  

1. This is consistent with usage elsewhere in fsx
2. This makes it clear that this is the path, not just the name.

### What do you think is the correct solution?

Change the property name in code and documentation.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Naming things is hard...

**Comment by nzakas** [comment]
fsx returns just the file or directory name as `name`, not the full path. You can see that in the [tests](https://github.com/humanwhocodes/fsx/blob/cce67e0fa0f0ababc0b802b84101306ec168fd5e/packages/test/src/fsx-impl-tester.js#L474-L493). So, it seems like this is inline with what is expected, unless I'm missing something?

**Comment by nzakas** [comment]
humanfs already has the desired behavior, so closing.
