### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by fatMonkeyGao** [humanwhocodes/humanfs#61]
### Which packages are affected?

- [ ] `@humanfs/core`
- [X] `@humanfs/node`
- [ ] `@humanfs/deno`
- [ ] `@humanfs/memory`
- [ ] `@humanfs/web`
- [ ] `@humanfs/test`
- [ ] `@humanfs/types`

### Environment

Node version: 20.10.0
npm version: 10.2.3
Deno version: 
Operating System: windows

### What did you do?

I encountered an error when referencing fsx-node in my Next.js project.

### What did you expect to happen?

I want to load the content from my own md files.

### What actually happened?

Module not found: Default condition should be last one
> 1 | import { fsx } from "fsx-node";

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-55axrh?file=app%2Fpage.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Thanks for the repro, that's very helpful. It looks like this is Next.js trying to load the module and not liking that the `default` export comes before `types` in `package.json`. Not sure why that matters, but I'll fix it.

Note: The new package name is `@humanfs`/node`.
