### ISSUE TITLE
Add functions to append to existing file

### ISSUE THREAD

**Issue by Valiantsin2021** [humanwhocodes/humanfs#65]
### Which packages would you like to change?

- [ ] `@humanfs/core`
- [X] `@humanfs/node`
- [X] `@humanfs/deno`
- [ ] `@humanfs/memory`
- [ ] `@humanfs/web`
- [ ] `@humanfs/test`
- [ ] `@humanfs/types`

### What problem do you want to solve?

Could be useful to append the info to already existing files (example - loggers), and to archive/unarchive files/folders (maybe zlib?)

### What do you think is the correct solution?

Create a method to append a file(txt) usind fs.promises.appendFile, and method to archive/unarchive the file/folder using zlib

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
This looks like two requests: one for appending to a file and one for gzipping. (In the future, please stick to one request per issue to avoid confusion.)

Gzipping is outside the scope of the project as it isn't a native filesystem operation and wouldn't, for example, make sense in the context of the browser or in cloud drives.

**Comment by Valiantsin2021** [comment]
You are right. Thanks.
