### ISSUE TITLE
Cannot read current directory with `@humanfs/memory`

### ISSUE THREAD

**Issue by Deckluhm** [humanwhocodes/humanfs#66]
### Which packages are affected?

- [ ] `@humanfs/core`
- [ ] `@humanfs/node`
- [ ] `@humanfs/deno`
- [X] `@humanfs/memory`
- [x] `@humanfs/web`
- [ ] `@humanfs/test`
- [ ] `@humanfs/types`

### Environment

Node version: **21.6.1**
npm version: **10.4.0**
Deno version: N/A
Operating System: WSL (**Ubuntu 22.04** on Windows 11)

### What did you do?

While writing unit tests using `@humanfs/memory`, I wanted to read the current directory using `hfs.list('.')` but it failed (while it works with `@humanfs/node`).

### What did you expect to happen?

I expected it to work just like it does with `@humanfs/node` since it's a valid path.

### What actually happened?

It throws ``TypeError(`name cannot be "."`)``.

### Link to Minimal Reproducible Example

https://github.com/Deckluhm/hfs-list-current-directory

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I didn't tested other implementations since I'm only using `@humanfs/node` and `@humanfs/memory` for unit tests.

**Comment by nzakas** [comment]
Thanks! I think I wasn't sure whether I could support `.` in that package initially, but it seems like you should be able to iterate over the top-level directory using `list()`. I'll take a look.

**Comment by nzakas** [comment]
As an update: `@humanfs/web` has the same issue, so I'll fix that too.
