### ISSUE TITLE
Brainstorm a new name

### ISSUE THREAD

**Issue by nzakas** [humanwhocodes/humanfs#8]
Sadly, Amazon released a product called [FSx](https://aws.amazon.com/fsx/), so I need to find a new name.

I'd really like to keep it at two or three characters.

I'm open to suggestions!

**Comment by MorganConrad** [comment]
FS2?  FS+?

**Comment by filiptammergard** [comment]
`xfs` to make it simple?

`mfs`? "modern file system"

`fsjs`?

**Comment by ljmerza** [comment]
afs for async fs

**Comment by nzakas** [comment]
Thanks everyone. Indeed, the main problem is that most three-letter sequences containing "fs" are already taken in some way. I went through a bunch before releasing ("zfs", "xfs") that ended up already related to some filesystem.

`fsz` is a possibility?

As a note: it's ridiculously hard to get an npm organization with a short name. Ideally the packages would be scoped but I couldn't find an available organization that would make sense, and didn't want to do humanwhocodes as it's soooooo long. :)

**Comment by blargoner** [comment]
I like `fsz`.

If Greek letters were practical here I'd suggest `µfs` given your [search](https://en.wikipedia.org/wiki/%CE%9C_operator) for a simple API. 😃

**Comment by RMcNeely** [comment]
I like @lobaorn 's suggestion about something riffing on ParetoFS or PlainFS. Another option that seems to be open on npm (based on some real quick searching) is `modfs`

**Comment by tombigel** [comment]
It’s an fs implementation by “human who codes” and ita purpose is to make fs api more human readable.. so `human-fs` or maybe “FS for Humans” - `fsfh` :)

**Comment by darrylnoakes** [comment]
Unfortunately, `hwc` is already a username on NPM, otherwise I'd definitely suggest that as an org.

**Comment by humbertaco** [comment]
Hi everyone! 

I just read your post about `fsx`, very interesting thoughts in there! 

I was curious about it and came across this discussion. Great suggestions from everyone! I kind of like `fsz`. The name proposed by @lobaorn is quite creative, although the term Pareto gives me more of mathematical vibes.

If the name does not have to start with fs, then I would propose `sfs` which could stand for simple (or succinct) filesystem, as it seems to me this is the core idea that you have been working out.

**Comment by mAAdhaTTah** [comment]
bfs - better fs? or btfs (since looks like npm.im/bfs exits). Dunno if that's too close to btrfs tho.

**Comment by yanghuabei** [comment]
efs - Efficient fs.

**Comment by MorganConrad** [comment]
One more, inspired by Colin Chapman, whose car design philosophy was "Simplify, then add lightness”

fssl    (another plus - it's available on NPM)

**Comment by nzakas** [comment]
Other options shared by @pamelafox:

> Naming ideas- filelib, fyllo (in honor of spanokipita i ate last night), filey, highfile (high level file ops), easyfs

**Comment by johandalabacka** [comment]
filesystem. Where is a package but it is 10 years since last update. https://www.npmjs.com/package/filesystem
Try to contact the person and see if he will transfer it to you

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account


or just a longer name modern-filesystem

**Comment by nzakas** [comment]
At the moment, I think my two favorites are humanfs and highfile.

**Comment by icylace** [comment]
I think "humanfs" is more consistent, branding-wise.

Also, https://www.highfile.com/ exists.

**Comment by loilo** [comment]
Just as a side note: Amazingly, the "human" username on npm is not taken yet, so you could easily create a free organization at that name and publish `@human/fs-node`. 🤭

**Comment by nzakas** [comment]
@icylace thanks for pointing that out. Sigh.

@loilo that is interesting! By the time I went and checked, it was already taken. Lesson learned: only post suggestions *after* reserving the org. 😆

**Comment by nzakas** [comment]
So if humanfs is the winner, would people expect `hfs` to be the singleton? And `Hfs` as the class?

I could also see exporting `fs` as the singleton, but I'm worried that might be confusing vs. the Node.js `fs` module.

**Comment by nzakas** [comment]
All right, so the library will be changed to humanfs, the main singleton will be `hfs`, and the main class with be `Hfs`.
